package client

import (
	"context"
	"regexp"
	"strconv"
)

// RepoFullNamePattern is the model's owner/repo rule: two non-empty segments
// with no whitespace or further slashes.
var RepoFullNamePattern = regexp.MustCompile(`^[^/\s]+/[^/\s]+$`)

// GithubIntegration links a project to a GitHub repository. The signing
// secret is write-only: it is sent on create (or generated by Flightdeck when
// omitted) and never returned. WebhookRegistered reports whether Flightdeck
// registered the repository webhook through its GitHub App (true when the
// secret was generated) or the caller manages the webhook (false).
type GithubIntegration struct {
	ID                int64  `json:"id"`
	ProjectID         int64  `json:"project_id"`
	RepoFullName      string `json:"repo_full_name"`
	Enabled           bool   `json:"enabled"`
	WebhookRegistered bool   `json:"webhook_registered"`
	LockVersion       int64  `json:"lock_version"`
	CreatedAt         string `json:"created_at"`
	UpdatedAt         string `json:"updated_at"`
}

// ResourceID implements Identified.
func (g *GithubIntegration) ResourceID() int64 { return g.ID }

const githubIntegrationRoot = "github_integration"

func githubIntegrationsPath(projectID int64) string {
	return "/projects/" + strconv.FormatInt(projectID, 10) + "/github-integrations"
}

func githubIntegrationPath(id int64) string {
	return "/github-integrations/" + strconv.FormatInt(id, 10)
}

// ListGithubIntegrations returns a project's GitHub integrations.
func (c *Client) ListGithubIntegrations(ctx context.Context, projectID int64) ([]GithubIntegration, error) {
	return ListResources[GithubIntegration](ctx, c, githubIntegrationsPath(projectID), githubIntegrationRoot)
}

// GetGithubIntegration fetches one integration.
func (c *Client) GetGithubIntegration(ctx context.Context, id int64) (*GithubIntegration, error) {
	return GetResource[*GithubIntegration](ctx, c, githubIntegrationPath(id), githubIntegrationRoot)
}

// CreateGithubIntegration links a repository through the verified create path.
// A repository the GitHub App cannot reach is a 422 repo_unreachable (no row
// created); a repository already linked to an enabled integration in the
// workspace is repo_already_linked.
func (c *Client) CreateGithubIntegration(ctx context.Context, projectID int64, fields Fields, idempotencyKey string) (*GithubIntegration, error) {
	return CreateResource(ctx, c, githubIntegrationsPath(projectID), githubIntegrationRoot, fields, idempotencyKey,
		VerifyByGet(c.GetGithubIntegration))
}

// UpdateGithubIntegration PATCHes an integration with an If-Match precondition.
func (c *Client) UpdateGithubIntegration(ctx context.Context, id int64, fields Fields, lockVersion int64) (*GithubIntegration, error) {
	return PatchResource[*GithubIntegration](ctx, c, githubIntegrationPath(id), githubIntegrationRoot, fields, &lockVersion)
}

// DeleteGithubIntegration unlinks the repository under an If-Match
// precondition; the API clears the project's github_repo_full_name when it
// matches. 404 is success.
func (c *Client) DeleteGithubIntegration(ctx context.Context, id, lockVersion int64) error {
	err := c.Delete(ctx, githubIntegrationPath(id), nil, WithIfMatch(lockVersion))
	if err != nil && !IsNotFound(err) {
		return err
	}
	return nil
}
